# Generated by Django 3.0.2 on 2020-01-20 18:32

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='about', verbose_name='Մեր մասին նկար')),
                ('body_l_hy', ckeditor.fields.RichTextField(blank=True, max_length='3000', verbose_name='Մեր մասին տեքստ (hy) ձախ')),
                ('body_l_ru', ckeditor.fields.RichTextField(blank=True, max_length='3000', verbose_name='Մեր մասին տեքստ (ru) ձախ')),
                ('body_l_en', ckeditor.fields.RichTextField(blank=True, max_length='3000', verbose_name='Մեր մասին տեքստ (en) ձախ')),
                ('body_r_hy', ckeditor.fields.RichTextField(blank=True, max_length='3000', verbose_name='Մեր մասին տեքստ (hy) աջ')),
                ('body_r_ru', ckeditor.fields.RichTextField(blank=True, max_length='3000', verbose_name='Մեր մասին տեքստ (ru) աջ')),
                ('body_r_en', ckeditor.fields.RichTextField(blank=True, max_length='3000', verbose_name='Մեր մասին տեքստ (en) աջ')),
            ],
            options={
                'verbose_name': 'Բժշկի մասին',
                'verbose_name_plural': 'Բժշկի մասին',
            },
        ),
        migrations.CreateModel(
            name='CheckedDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, verbose_name='Ամիս ամսաթիվ')),
            ],
            options={
                'verbose_name': 'Աշխատանքային օր',
                'verbose_name_plural': 'Աշխատանքային օրեր',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=25, verbose_name='Հեռախոսահամա')),
                ('whatsapp', models.CharField(db_index=True, max_length=30, verbose_name='WhatsApp')),
                ('whatsapp_link', models.CharField(db_index=True, max_length=25, verbose_name='WhatsApp (Առանց  և բացատի)')),
                ('viber', models.CharField(db_index=True, max_length=30, verbose_name='Viber')),
                ('viber_link', models.CharField(db_index=True, max_length=25, verbose_name='Viber (Առանց  և բացատի)')),
                ('fb', models.CharField(db_index=True, max_length=100, verbose_name='Facebook')),
                ('mail', models.CharField(db_index=True, max_length=50, verbose_name='Mail')),
                ('address_hy', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Հասցե (hy)')),
                ('address_ru', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Հասցե (ru)')),
                ('address_en', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Հասցե (en)')),
            ],
            options={
                'verbose_name': 'Կոնտակտ',
                'verbose_name_plural': 'Կոնտակտներ',
            },
        ),
        migrations.CreateModel(
            name='GeneralServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_hy', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Ծառայության անուն (hy)')),
                ('name_ru', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Ծառայության անուն (ru)')),
                ('name_en', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Ծառայության անուն (en)')),
                ('body_hy', ckeditor.fields.RichTextField(blank=True, max_length=7000, verbose_name='Ծառայության մասին (hy)')),
                ('body_ru', ckeditor.fields.RichTextField(blank=True, max_length=7000, verbose_name='Ծառայության մասին (ru)')),
                ('body_en', ckeditor.fields.RichTextField(blank=True, max_length=7000, verbose_name='Ծառայության մասին (en)')),
                ('img', models.ImageField(upload_to='services', verbose_name='Ծառայության նկար')),
            ],
            options={
                'verbose_name': 'Գովազդային ծառայություն',
                'verbose_name_plural': 'Գովազդային ծառայություն',
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_hy', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Հիվանդության անունը (hy)')),
                ('name_ru', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Հիվանդության անունը (ru)')),
                ('name_en', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Հիվանդության անունը (en)')),
                ('info_hy', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Հիվանդությունների մասին և այլն (hy)')),
                ('info_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Հիվանդությունների մասին և այլն (ru)')),
                ('info_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Հիվանդությունների մասին և այլն (en)')),
            ],
            options={
                'verbose_name': 'Հիվանդությունների մասին և այլն',
                'verbose_name_plural': 'Հիվանդությունների մասին և այլն',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_hy', models.TextField(blank=True, max_length=4000, verbose_name='Ակնարկներ (hy)')),
                ('content_ru', models.TextField(blank=True, max_length=4000, verbose_name='Ակնարկներ (ru)')),
                ('content_en', models.TextField(blank=True, max_length=4000, verbose_name='Ակնարկներ (en)')),
                ('name_hy', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Անուն Ազգանուն (hy)')),
                ('name_ru', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Անուն Ազգանուն (ru)')),
                ('name_en', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Անուն Ազգանուն (en)')),
                ('disease_hy', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Բուժված հիվանդությունը (hy)')),
                ('disease_ru', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Բուժված հիվանդությունը (ru)')),
                ('disease_en', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Բուժված հիվանդությունը (en)')),
                ('published', models.BooleanField(verbose_name='Հրապարակել')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Կարծիք',
                'verbose_name_plural': 'Կարծիքներ',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='SectionGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_hy', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='Անուն Ազգանուն (hy)')),
                ('name_ru', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='Անուն Ազգանուն (ru)')),
                ('name_en', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='Անուն Ազգանուն (en)')),
                ('info_hy', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Պաշտոն և այլն (hy)')),
                ('info_ru', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Պաշտոն և այլն (ru)')),
                ('info_en', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Պաշտոն և այլն (en)')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='Հեռախոսահամար')),
                ('img', models.ImageField(upload_to='general', verbose_name='Նկար')),
            ],
            options={
                'verbose_name': 'Բժշկի անձնական տվյալներ',
                'verbose_name_plural': 'Բժշկի անձնական տվյալներ',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_hy', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Ծառայության անուն (hy)')),
                ('name_ru', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Ծառայության անուն (ru)')),
                ('name_en', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Ծառայության անուն (en')),
                ('body_hy', ckeditor.fields.RichTextField(blank=True, max_length=3000, verbose_name='Ծառայության մասին (hy)')),
                ('body_ru', ckeditor.fields.RichTextField(blank=True, max_length=3000, verbose_name='Ծառայության մասին (ru)')),
                ('body_en', ckeditor.fields.RichTextField(blank=True, max_length=3000, verbose_name='Ծառայության մասին (en)')),
                ('img', models.ImageField(upload_to='services', verbose_name='Ծառայության նկար')),
            ],
            options={
                'verbose_name': 'Ծառայություններ',
                'verbose_name_plural': 'Ծառայություններ',
            },
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='works/%Y/%m/%d', verbose_name='Մեր գործերը նկար')),
                ('url', models.CharField(blank=True, max_length=1000, verbose_name='Մեր գործերը լինք')),
            ],
            options={
                'verbose_name': 'Կատարված աշխատանք',
                'verbose_name_plural': 'Կատարված աշխատանքներ',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CheckedTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('10:00-10:30', '10:00-10:30'), ('10:30-11:00', '10:30-11:00'), ('11:00-11:30', '11:00-11:30'), ('11:30-12:00', '11:30-12:00'), ('12:00-12:30', '12:00-12:30'), ('12:30-13:00', '12:30-13:00'), ('13:00-13:30', '13:00-13:30'), ('13:30-14:00', '13:30-14:00'), ('14:00-14:30', '14:00-14:30'), ('14:30-15:00', '14:30-15:00'), ('15:00-15:30', '15:00-15:30'), ('15:30-16:00', '15:30-16:00'), ('16:00-16:30', '16:00-16:30'), ('16:30-17:00', '16:30-17:00')], max_length=12, verbose_name='Ժամ')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CheckedDate')),
            ],
            options={
                'verbose_name': 'Աշխատանքային ժամ',
                'verbose_name_plural': 'Աշխատանքային ժամեր',
            },
        ),
    ]
